import React from 'react';

export const currencies = ['USD', 
                    'EUR', 
                    'GBP', 
                    'JPY', 
                    'CAD', 
                    'AUD', 
                    'NZD', 
                    'CHF', 
                    'SEK', 
                    'NOK', 
                    'DKK', 
                    'CZK', 
                    'HUF', 
                    'PLN', 
                    'ISK', 
                    'HRK', 
                    'RON', 
                    'BGN', 
                    'TRY', 
                    'ILS', 
                    'PHP', 
                    'IDR', 
                    'MYR', 
                    'THB', 
                    'ZAR', 
                    'BRL', 
                    'MXN', 
                    'ARS', 
                    'CLP', 
                    'COP', 
                    'PEN', 
                    'UYU', 
                    'VES'];